version: "3"
services:
  postgres:
    image: postgres:10.1-alpine
    container_name: postgres
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
